version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py  # 指定 Sphinx 的配置文件路径

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml  # 指定 MkDocs 的配置文件路径

# Install dependencies
python:
  install:
    - requirements: requirements.txt  # 指定需要安装的 Python 依赖

build:
  os: ubuntu-20.04  # 指定操作系统
  tools:
    python: "3.8"  # 指定 Python 版本
